### ISSUE TITLE
Limit the number of alerts open in same screen

### ISSUE THREAD

**Issue by misner** [HubSpot/messenger#101]
I have a basic huspot messenger alert (see below).
Every time a user click, the little alert open.

The issue is if a user clicks like 10 times, the screen, particularly on a mobile device, get "too" full of alerts windows and you can't read the real webpage behind it anymore.

How can I limit the number of open / visible alerts to 3 for example?

Messenger().post({  
    message: 'my message',
    type: 'error',
    actions: {
      continueExternally: {
        label: "go here,
        action: function(){
          location.href = 'localhost:3000';          
        }
      },
      continueToExperience: {
        label: 'do more',
        action: function(){
          location.href = 'http:/:example.com';          
        }
       
      }
    }
});	

thanks for any help

**Comment by zackbloom** [comment]
See the options here: http://github.hubspot.com/messenger/

Particularly the 'id' option if you only want one instance of a given message, and the 'maxMessages' option if you want to restrict the total number of messages visible at once.

**Comment by misner** [comment]
thanks, i actually had read it but managed not to spot it.
thanks
