### ISSUE TITLE
Publish on NPM

### ISSUE THREAD

**Issue by Copywright** [HubSpot/messenger#106]
Surprised to see this isn't listed on NPM.

**Comment by gesposito** [comment]
npm supports 
`npm install -S https://github.com/HubSpot/messenger`

**Comment by Copywright** [comment]
^^ Did not know that! thanks.

**Comment by gesposito** [comment]
yw, not the exact same thing, but it helps.

**Comment by geekjuice** [comment]
Another shorthand for the above is just `npm install -S HubSpot/messenger`. Unfortunately, the package name `messenger` is taken, so until we can determine an appropriate name for `messenger` on `npm`, the named package is the recommended way to install.
