### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by infacq** [HubSpot/messenger#79]
not sure how or what to inspect when it's loaded on the application. Is there any memory leak? how to ensure it being dispose?

**Comment by geekjuice** [comment]
To be perfectly honest, there may be memory leaks in certain edge case scenarios (but none that I have encountered thus far). If you would like to start monitoring though if `Messenger` may have potential memory leaks, I suggest downloading a browser that has some developer tools to help profile those issues. Personally, I suggest __Google Chrome__ and using their _Profile_ tool in _Dev Tools_. You can get started using the _Profile_ tool [here](https://developer.chrome.com/devtools/docs/javascript-memory-profiling). If you do discover leaks in `Messenger` that we are not properly disposing, feel free to open up a new issue and we'll be sure to take a look and help out.
