### ISSUE TITLE
Extra classes for actions and close button

### ISSUE THREAD

**Issue by ardoramor** [HubSpot/messenger#82]
Although the examples show that you can bind events to actions with classes, the code does not support assignment of classes to actions. It would be good to add `extraClasses` parameter to per-action configuration. Also, extra classes for the close button.

**Comment by geekjuice** [comment]
Is there a particular use case you would need `extraClasses`? If it's for styling purposes, you could access each element via `[data-action="{action}"]` and the close button via `[data-dismiss="alert"]`. Other than that, adding extra classes to every portion of a `Messenger` dialog seems like overkill and added complexity.
