### ISSUE TITLE
Disallow message from disappearing until close button clicked

### ISSUE THREAD

**Issue by gladwinput** [HubSpot/messenger#91]
Love this code.
But what if I don't want it to disappear eventually? Say I am using it for a tutorial but I don't want it to go away until I tell it to with a prompt (user clicks something I ask them to etc). How do I force it to stay open?

**Comment by TrevorBurnham** [comment]
Use the option

    hideAfter: 0

**Comment by gladwinput** [comment]
Quality, thank you!

**Comment by gladwinput** [comment]
Also - I just discovered Shepherd. You guys are machines!
