### ISSUE TITLE
How to use with $get or Ajax request?

### ISSUE THREAD

**Issue by biapar** [HubSpot/messenger#92]
How to use with $get or Ajax request?
Thx

**Comment by geekjuice** [comment]
If you take a look at the [documentation](http://github.hubspot.com/messenger/docs/welcome/), we actually provide many examples on how to use `messenger` in various ways. In fact, the first example shows how to use it with an ajax request and below are a few other examples as well. Hopefully you find what you need in there.

**Comment by biapar** [comment]
Yes, I read the docs before. Do I change if all $.ajax calls into the code or not?

**Comment by geekjuice** [comment]
Do you mind providing an example of what you are trying to accomplish? A [jsFiddle](https://jsfiddle.net/) would be even better. 

In the meantime, if I were to guess what you were asking for, I would probably say the answer is __no__, you do not need to replace all `$.ajax`, just the ones you want `messenger` to alert for on success/error of the response. For example:

```javascript
let messages = {
  successMessage: "Roger that!",
  errorMessage: "Abort mission!"
};

Messenger().run(messages, {
  url: '/ready',
  success(response, type, xhr) {
   successHandler(response);
  },
  error(xhr, type, statusText) {
    errorHandler(xhr);
  }
});

```

If your response was a success, `messenger` will display the `successMessage` and in the `success` callback, you can do whatever you need to with the response (as if from `$.ajax`). Likewise for the when the response fails. Basically the above is equivalent to: 

```javascript
$.ajax({
  url: '/ready',
  type: 'GET',
  dataType: 'json',
  success(response, type, xhr) {
    Messenger().post(messages.successMessage);
    successHandler(response);
  },
  error(xhr, type, statusText) {
    Messenger().post(messages.errorMessage);
    errorHandler(xhr);
  }
});
```
